// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.WS.API.DatabaseModels;

[Table("Buildings", Schema = "Lookup")]
public partial class Building
{
    [Key]
    public int BuildingId { get; set; }

    [Unicode(false)]
    public string BuildingName { get; set; }

    public int? FactionId { get; set; }

    [InverseProperty("Building")]
    public virtual ICollection<ConstructedBuilding> ConstructedBuildings { get; } = new List<ConstructedBuilding>();

    [ForeignKey("FactionId")]
    [InverseProperty("Buildings")]
    public virtual Faction Faction { get; set; }
}