// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Abio.WS.API.DatabaseModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Abio.WS.API.DatabaseModels
{
    public partial interface IAbioContextProcedures
    {
    }
}
