// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.WS.API.DatabaseModels;

[Table("Technology", Schema = "Lookup")]
public partial class Technology
{
    [Key]
    public int TechnologyId { get; set; }

    [Unicode(false)]
    public string TechnologyName { get; set; }

    [InverseProperty("Technology")]
    public virtual ICollection<ResearchedTechnology> ResearchedTechnologies { get; } = new List<ResearchedTechnology>();
}