// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.WS.API.DatabaseModels;

[Table("Users", Schema = "Security")]
public partial class User
{
    [Key]
    public Guid UserId { get; set; }

    [Required]
    [Column("created_at")]
    public byte[] CreatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<ConstructedBuilding> ConstructedBuildings { get; } = new List<ConstructedBuilding>();

    [InverseProperty("FriendsWithNavigation")]
    public virtual ICollection<Friend> Friends { get; } = new List<Friend>();

    [InverseProperty("User")]
    public virtual ICollection<HiredLeader> HiredLeaders { get; } = new List<HiredLeader>();

    [InverseProperty("User")]
    public virtual ICollection<HiredUnit> HiredUnits { get; } = new List<HiredUnit>();

    [InverseProperty("User")]
    public virtual ICollection<ItemInventory> ItemInventories { get; } = new List<ItemInventory>();

    [InverseProperty("User")]
    public virtual ICollection<MarketListing> MarketListings { get; } = new List<MarketListing>();

    [InverseProperty("User")]
    public virtual Player Player { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<ResearchedTechnology> ResearchedTechnologies { get; } = new List<ResearchedTechnology>();

    [InverseProperty("User")]
    public virtual ICollection<ResourceInventory> ResourceInventories { get; } = new List<ResourceInventory>();

    [InverseProperty("User")]
    public virtual ICollection<UserCity> UserCities { get; } = new List<UserCity>();

    [InverseProperty("User")]
    public virtual ICollection<UserCitiesLeader> UserCitiesLeaders { get; } = new List<UserCitiesLeader>();
}