// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Attribute
{
    public int AttributeId { get; set; }

    public string AttributeName { get; set; }

    public string AttributeDescription { get; set; }
}