// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class BodyPart
{
    public int BodyPartId { get; set; }

    public string BodyPartName { get; set; }

    public string BodyPartDescription { get; set; }
}