// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class BuildingLevel
{
    public int BuildingLevelId { get; set; }

    public string BuildingLevelName { get; set; }

    public string BuildingLevelDescription { get; set; }

    public virtual ICollection<ConstructedBuilding> ConstructedBuilding { get; set; } = new List<ConstructedBuilding>();
}