// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Emotion
{
    public int EmotionId { get; set; }

    public string EmotionName { get; set; }

    public string EmotionDescription { get; set; }
}