// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Feat
{
    public int FeatId { get; set; }

    public string FeatName { get; set; }

    public string FeatDescription { get; set; }
}