// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Item
{
    public Guid ItemId { get; set; }

    public string ItemName { get; set; }

    public string ItemDescription { get; set; }

    public virtual ICollection<ItemInventory> ItemInventory { get; set; } = new List<ItemInventory>();

    public virtual ICollection<MarketListing> MarketListing { get; set; } = new List<MarketListing>();
}