// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class PersonalityTrait
{
    public int PersonalityTraitId { get; set; }

    public string PersonalityTraitName { get; set; }

    public string PersonalityTraitDescription { get; set; }
}