// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class ConstructedBuilding
{
    public Guid ConstructedBuildingId { get; set; }

    public int? BuildingId { get; set; }

    public Guid? UserId { get; set; }

    public int? BuildingLevelId { get; set; }

    public DateTime? created_at { get; set; }

    public virtual Building Building { get; set; }

    public virtual BuildingLevel BuildingLevel { get; set; }

    public virtual ResourceGain ResourceGain { get; set; }

    public virtual User User { get; set; }
}