// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnitStat
{
    public Guid HiredUnitStatId { get; set; }

    public Guid? HiredUnitStatCombatId { get; set; }

    public Guid? HiredUnitStatCivilId { get; set; }

    public Guid? HiredUnitStatMagicId { get; set; }

    public Guid? HiredUnitStatBodyId { get; set; }

    public Guid? HiredUnitStatEmotionId { get; set; }

    public Guid? HiredUnitStatFeatId { get; set; }

    public virtual ICollection<HiredUnit> HiredUnit { get; set; } = new List<HiredUnit>();

    public virtual HiredUnitStatBody HiredUnitStatBody { get; set; }

    public virtual HiredUnitStatCivil HiredUnitStatCivil { get; set; }

    public virtual HiredUnitStatCombat HiredUnitStatCombat { get; set; }

    public virtual HiredUnitStatEmotion HiredUnitStatEmotion { get; set; }

    public virtual HiredUnitStatFeat HiredUnitStatFeat { get; set; }

    public virtual HiredUnitStatMagic HiredUnitStatMagic { get; set; }
}