// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnit
{
    public Guid HiredUnitId { get; set; }

    public string Name { get; set; }

    public byte? Age { get; set; }

    public int? UnitId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? HiredUnitStatId { get; set; }

    public virtual HiredUnitStat HiredUnitStat { get; set; }

    public virtual Unit Unit { get; set; }

    public virtual User User { get; set; }
}