// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnitStatCivil
{
    public Guid HiredUnitStatCivilId { get; set; }

    public byte? Horsemanship { get; set; }

    public byte? Mining { get; set; }

    public byte? Quarrying { get; set; }

    public byte? Woodcutting { get; set; }

    public byte? Farming { get; set; }

    public byte? Leatherworking { get; set; }

    public byte? Clothier { get; set; }

    public byte? Cobbling { get; set; }

    public byte? Hatter { get; set; }

    public byte? Blacksmithing { get; set; }

    public byte? Fletching { get; set; }

    public byte? Artifice { get; set; }

    public byte? Alchemy { get; set; }

    public byte? Medicine { get; set; }

    public byte? Construction { get; set; }

    public byte? Planning { get; set; }

    public byte? Adaptability { get; set; }

    public byte? CriticalThinking { get; set; }

    public byte? Negotiation { get; set; }

    public byte? Leadership { get; set; }

    public byte? Teamwork { get; set; }

    public byte? Deception { get; set; }

    public byte? Persuasion { get; set; }

    public byte? Comedy { get; set; }

    public byte? Painting { get; set; }

    public byte? Writing { get; set; }

    public byte? Music { get; set; }

    public virtual ICollection<HiredUnitStat> HiredUnitStat { get; set; } = new List<HiredUnitStat>();
}