// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnitStatCombat
{
    public Guid HiredUnitStatCombatId { get; set; }

    public byte? Unarmed { get; set; }

    public byte? ShortBlade { get; set; }

    public byte? LongBlade { get; set; }

    public byte? Staff { get; set; }

    public byte? ThrownWeapons { get; set; }

    public byte? Archery { get; set; }

    public byte? Siege { get; set; }

    public byte? Shield { get; set; }

    public byte? MeleeDefence { get; set; }

    public byte? RangedDefence { get; set; }

    public byte? Ward { get; set; }

    public byte? Unarmored { get; set; }

    public byte? LightArmor { get; set; }

    public byte? HeavyArmor { get; set; }

    public byte? Dueling { get; set; }

    public byte? DualWielding { get; set; }

    public virtual ICollection<HiredUnitStat> HiredUnitStat { get; set; } = new List<HiredUnitStat>();
}