// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnitStatFeat
{
    public Guid HiredUnitStatFeatId { get; set; }

    public bool? HasSurvivor { get; set; }

    public bool? HasQuick { get; set; }

    public bool? HasSavant { get; set; }

    public bool? HasNoble { get; set; }

    public virtual ICollection<HiredUnitStat> HiredUnitStat { get; set; } = new List<HiredUnitStat>();
}