// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnitStatEmotion
{
    public Guid HiredUnitStatEmotionId { get; set; }

    public byte? Happy { get; set; }

    public byte? Angry { get; set; }

    public byte? Sad { get; set; }

    public byte? Fear { get; set; }

    public virtual ICollection<HiredUnitStat> HiredUnitStat { get; set; } = new List<HiredUnitStat>();
}