// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class ResourceGain
{
    public Guid ResourceGainId { get; set; }

    public int ResourceId { get; set; }

    public DateTime TimeSinceLastGathered { get; set; }

    public Guid UserId { get; set; }

    public virtual Resource Resource { get; set; }

    public virtual User User { get; set; }
}