// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Abio.Library.DatabaseModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Abio.Library.DatabaseModels
{
    public partial class AbioContext
    {
        private IAbioContextProcedures _procedures;

        public virtual IAbioContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AbioContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAbioContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class AbioContextProcedures : IAbioContextProcedures
    {
        private readonly AbioContext _context;

        public AbioContextProcedures(AbioContext context)
        {
            _context = context;
        }
    }
}
