// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class BuildingsLevel
{
    public int BuildingLevelId { get; set; }

    public string BuildingRankName { get; set; }

    public virtual ICollection<ConstructedBuilding> ConstructedBuildings { get; } = new List<ConstructedBuilding>();
}