// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Building
{
    public Guid BuildingId { get; set; }

    public string BuildingName { get; set; }

    public int? FactionId { get; set; }
}