// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.Library.DatabaseModels;

[Table("BuildingsLevels", Schema = "Lookup")]
public partial class BuildingsLevel
{
    [Key]
    public int BuildingLevelId { get; set; }

    [Unicode(false)]
    public string BuildingRankName { get; set; }

    [InverseProperty("BuildingLevelNavigation")]
    public virtual ICollection<ConstructedBuilding> ConstructedBuildings { get; } = new List<ConstructedBuilding>();
}