// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnitStat
{
    public Guid HiredUnitStatId { get; set; }

    public Guid? HiredUnitId { get; set; }

    public int? Leadership { get; set; }

    public int? Attack { get; set; }

    public int? Defense { get; set; }

    public int? MovementSpeed { get; set; }

    public int? AttackSpeed { get; set; }

    public int? MeleeRange { get; set; }

    public int? RangedRange { get; set; }

    public virtual HiredUnit HiredUnit { get; set; }
}