// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.Library.DatabaseModels;

[Table("HiredUnits", Schema = "Player")]
public partial class HiredUnit
{
    [Key]
    public Guid HiredUnitId { get; set; }

    public Guid? UserId { get; set; }

    public int? UnitId { get; set; }

    public int? UnitLevel { get; set; }

    public Guid? HiredLeaderId { get; set; }

    [Required]
    [Column("created_at")]
    public byte[] CreatedAt { get; set; }

    [ForeignKey("HiredLeaderId")]
    [InverseProperty("HiredUnits")]
    public virtual HiredLeader HiredLeader { get; set; }

    [InverseProperty("HiredUnit")]
    public virtual ICollection<HiredUnitsStat> HiredUnitsStats { get; } = new List<HiredUnitsStat>();

    [ForeignKey("UnitId")]
    [InverseProperty("HiredUnits")]
    public virtual Unit Unit { get; set; }

    [InverseProperty("HiredUnit")]
    public virtual ICollection<UnitGroup> UnitGroups { get; } = new List<UnitGroup>();

    [ForeignKey("UnitLevel")]
    [InverseProperty("HiredUnits")]
    public virtual UnitLevel UnitLevelNavigation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("HiredUnits")]
    public virtual User User { get; set; }
}