// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.Library.DatabaseModels;

[Table("HiredLeaders", Schema = "Player")]
public partial class HiredLeader
{
    [Key]
    public Guid HiredLeaderId { get; set; }

    public Guid? UserId { get; set; }

    [StringLength(24)]
    [Unicode(false)]
    public string HiredLeaderName { get; set; }

    public Guid? LeaderStatId { get; set; }

    [Required]
    [Column("created_at")]
    public byte[] CreatedAt { get; set; }

    [InverseProperty("HiredLeader")]
    public virtual ICollection<HiredLeaderStat> HiredLeaderStats { get; } = new List<HiredLeaderStat>();

    [InverseProperty("HiredLeader")]
    public virtual ICollection<HiredUnit> HiredUnits { get; } = new List<HiredUnit>();

    [InverseProperty("HiredLeader")]
    public virtual ICollection<UnitGroup> UnitGroups { get; } = new List<UnitGroup>();

    [ForeignKey("UserId")]
    [InverseProperty("HiredLeaders")]
    public virtual User User { get; set; }

    [InverseProperty("HiredLeader")]
    public virtual ICollection<UserCitiesLeader> UserCitiesLeaders { get; } = new List<UserCitiesLeader>();
}