// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredUnit
{
    public Guid HiredUnitId { get; set; }

    public Guid? UserId { get; set; }

    public int? UnitId { get; set; }

    public int? UnitLevel { get; set; }

    public Guid? HiredLeaderId { get; set; }

    public byte[] created_at { get; set; }

    public virtual HiredLeader HiredLeader { get; set; }

    public virtual ICollection<HiredUnitStat> HiredUnitStat { get; } = new List<HiredUnitStat>();

    public virtual ICollection<UnitGroup> UnitGroup { get; } = new List<UnitGroup>();

    public virtual User User { get; set; }
}