// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class HiredLeader
{
    public Guid HiredLeaderId { get; set; }

    public Guid? UserId { get; set; }

    public string HiredLeaderName { get; set; }

    public Guid? LeaderStatId { get; set; }

    public byte[] created_at { get; set; }

    public virtual ICollection<HiredLeaderStat> HiredLeaderStat { get; set; } = new List<HiredLeaderStat>();

    public virtual ICollection<HiredUnit> HiredUnit { get; set; } = new List<HiredUnit>();

    public virtual ICollection<UnitGroup> UnitGroup { get; set; } = new List<UnitGroup>();

    public virtual User User { get; set; }

    public virtual ICollection<UserCityLeader> UserCityLeader { get; set; } = new List<UserCityLeader>();
}