// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class ItemInventory
{
    public Guid ItemInventoryId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? ItemId { get; set; }

    public long? Quantity { get; set; }

    public long? MaxInventory { get; set; }

    public virtual Item Item { get; set; }

    public virtual ICollection<MarketListing> MarketListings { get; } = new List<MarketListing>();

    public virtual User User { get; set; }
}