// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Player
{
    public Guid UserId { get; set; }

    public int? MaxCities { get; set; }

    public int? MaxOwnedLand { get; set; }

    public virtual User User { get; set; }
}