// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.Library.DatabaseModels;

[Table("ResearchedTechnology", Schema = "Player")]
public partial class ResearchedTechnology
{
    [Key]
    public Guid ResearchedTechnologyId { get; set; }

    public Guid? UserId { get; set; }

    public int? TechnologyId { get; set; }

    [Required]
    [Column("created_at")]
    public byte[] CreatedAt { get; set; }

    [ForeignKey("TechnologyId")]
    [InverseProperty("ResearchedTechnologies")]
    public virtual Technology Technology { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ResearchedTechnologies")]
    public virtual User User { get; set; }
}