// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class ResearchedTechnology
{
    public Guid? ResearchedTechnologyId { get; set; }

    public int? TechnologyId { get; set; }

    public byte[] created_at { get; set; }

    public virtual Technology Technology { get; set; }
}