// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Resource
{
    public Guid ResourceId { get; set; }

    public string ResourceName { get; set; }

    public virtual ICollection<ResourceInventory> ResourceInventory { get; set; } = new List<ResourceInventory>();
}