// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Abio.Library.DatabaseModels;

[Table("Resources", Schema = "Lookup")]
public partial class Resource
{
    [Key]
    public int ResourceId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ResourceName { get; set; }

    [InverseProperty("Resource")]
    public virtual ICollection<ResourceInventory> ResourceInventories { get; } = new List<ResourceInventory>();
}