// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class Technology
{
    public Guid TechnologyId { get; set; }

    public string TechnologyName { get; set; }
}