// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class UnitStat
{
    public Guid UnitStatId { get; set; }

    public Guid UnitId { get; set; }

    public int? ShortBlade { get; set; }

    public int? Unarmed { get; set; }

    public int? OneHanded { get; set; }

    public int? TwoHanded { get; set; }

    public int? Staff { get; set; }

    public int? ThrownWeapons { get; set; }

    public int? Bow { get; set; }

    public int? Rifle { get; set; }

    public int? Shield { get; set; }

    public int? MeleeDefence { get; set; }

    public int? RangedDefence { get; set; }

    public int? MagicDefense { get; set; }

    public int? Dueling { get; set; }

    public int? DualWielding { get; set; }

    public int? Bruiser { get; set; }

    public int? Tank { get; set; }

    public virtual Unit Unit { get; set; }
}