// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class UnitLevel
{
    public Guid UnitLevelId { get; set; }

    public string UnitRankName { get; set; }
}