// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace Abio.Library.DatabaseModels;

public partial class Unit
{
    public Guid UnitId { get; set; }

    public string UnitName { get; set; }

    public int FactionId { get; set; }

    public virtual ICollection<HiredUnit> HiredUnit { get; } = new List<HiredUnit>();

    public virtual ICollection<UnitAttribute> UnitAttribute { get; } = new List<UnitAttribute>();

    public virtual ICollection<UnitStat> UnitStat { get; } = new List<UnitStat>();
}