// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class UnitAttribute
{
    public Guid UnitAttributeId { get; set; }

    public Guid UnitId { get; set; }

    public int? Strength { get; set; }

    public int? Agility { get; set; }

    public int? Dexterity { get; set; }

    public int? Charisma { get; set; }

    public int? Intelligence { get; set; }

    public int? Willpower { get; set; }

    public int? Soul { get; set; }

    public int? Artistry { get; set; }

    public int? Creativity { get; set; }

    public int? Constitution { get; set; }

    public int? Sanity { get; set; }

    public virtual Unit Unit { get; set; }
}