// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class UnitLevel
{
    public int UnitLevelId { get; set; }

    public string UnitRankName { get; set; }

    public virtual ICollection<HiredUnit> HiredUnits { get; } = new List<HiredUnit>();
}