// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class User
{
    public Guid UserId { get; set; }

    public byte[] created_at { get; set; }

    public virtual ICollection<ConstructedBuilding> ConstructedBuilding { get; } = new List<ConstructedBuilding>();

    public virtual ICollection<Friend> Friend { get; } = new List<Friend>();

    public virtual ICollection<HiredLeader> HiredLeader { get; } = new List<HiredLeader>();

    public virtual ICollection<HiredUnit> HiredUnit { get; } = new List<HiredUnit>();

    public virtual ICollection<ItemInventory> ItemInventory { get; } = new List<ItemInventory>();

    public virtual ICollection<MarketListing> MarketListing { get; } = new List<MarketListing>();

    public virtual Player Player { get; set; }

    public virtual ICollection<ResearchedTechnology> ResearchedTechnology { get; } = new List<ResearchedTechnology>();

    public virtual ICollection<ResourceInventory> ResourceInventory { get; } = new List<ResourceInventory>();

    public virtual ICollection<UserCity> UserCity { get; } = new List<UserCity>();

    public virtual ICollection<UserCityLeader> UserCityLeader { get; } = new List<UserCityLeader>();
}