// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.DatabaseModels;

public partial class UserCitiesLeader
{
    public Guid UserCityLeadersId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? HiredLeaderId { get; set; }

    public Guid? CityId { get; set; }

    public virtual UserCity City { get; set; }

    public virtual HiredLeader HiredLeader { get; set; }

    public virtual User User { get; set; }
}