// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class ConstructedBuilding
{
    public Guid ConstructuredBuildingId { get; set; }

    public int? BuildingId { get; set; }

    public Guid? UserId { get; set; }

    public int? BuildingLevel { get; set; }

    public byte[] created_at { get; set; }

    public virtual Building Building { get; set; }

    public virtual BuildingsLevel BuildingLevelNavigation { get; set; }

    public virtual User User { get; set; }
}