// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class Faction
{
    public int FactionId { get; set; }

    public string FactionName { get; set; }

    public virtual ICollection<Building> Buildings { get; } = new List<Building>();

    public virtual ICollection<Unit> Units { get; } = new List<Unit>();
}