// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class HiredLeader
{
    public Guid HiredLeaderId { get; set; }

    public Guid? UserId { get; set; }

    public string HiredLeaderName { get; set; }

    public virtual User User { get; set; }
}