// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class HiredUnit
{
    public Guid HiredUnitId { get; set; }

    public Guid? UserId { get; set; }

    public int? UnitId { get; set; }

    public int? UnitLevel { get; set; }

    public byte[] created_at { get; set; }

    public virtual Unit Unit { get; set; }

    public virtual UnitLevel UnitLevelNavigation { get; set; }

    public virtual User User { get; set; }
}