// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class MarketListing
{
    public Guid ListingId { get; set; }

    public Guid? MarketId { get; set; }

    public Guid? ItemId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? ItemInventoryId { get; set; }

    public long? ItemQuantity { get; set; }

    public virtual Item Item { get; set; }

    public virtual ItemInventory ItemInventory { get; set; }

    public virtual Market Market { get; set; }

    public virtual User User { get; set; }
}