// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class Market
{
    public Guid MarketId { get; set; }

    public long? MarketCoordinatesX { get; set; }

    public long? MarketCoordinatesY { get; set; }

    public int? MarketRadius { get; set; }

    public string MarketName { get; set; }

    public bool? IsMainMarket { get; set; }

    public virtual ICollection<MarketListing> MarketListings { get; } = new List<MarketListing>();
}