// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Abio.Library.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public byte[] created_at { get; set; }

    public virtual ICollection<ConstructedBuilding> ConstructedBuildings { get; } = new List<ConstructedBuilding>();

    public virtual ICollection<Friend> Friends { get; } = new List<Friend>();

    public virtual ICollection<HiredLeader> HiredLeaders { get; } = new List<HiredLeader>();

    public virtual ICollection<HiredUnit> HiredUnits { get; } = new List<HiredUnit>();

    public virtual ICollection<ItemInventory> ItemInventories { get; } = new List<ItemInventory>();

    public virtual ICollection<MarketListing> MarketListings { get; } = new List<MarketListing>();

    public virtual ICollection<ResourceInventory> ResourceInventories { get; } = new List<ResourceInventory>();
}